### PR TITLE
OCP4 Migration and Jenkins Pipeline Updates

### PR DESCRIPTION
**Pull request by jujaga**
# Description

This PR updates the Jenkins pipeline and openshift templates to be OCP4 compatible.
- Includes a CommonPipeline loading fix which allows the pipeline to be restarted halfway through

[SHOWCASE-1864](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1864)
[SHOWCASE-1865](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1865)

## Types of changes

New feature (non-breaking change which adds functionality)
Documentation (non-breaking change with enhancements to documentation)
Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the OpenAPI 3.0 `v*.api-spec.yaml` documentation (if appropriate)
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://cdogs-dev-pr-55.apps.silver.devops.gov.bc.ca

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://cdogs-dev-pr-55.apps.silver.devops.gov.bc.ca

**Review by TimCsaky — APPROVED** [review]
good job Jeremy.
i tested the api and it works.

**Comment by jujaga** [comment]
> 
> 
> Can we do some checks in postman against the ocp3 and 4 deployments to make sure there isn't a performace drop from that CPU_REQUEST change?

The CPU request will have little to no realistic impact on API performance as that is a spike covered by CPU_LIMIT which remains the same at 1000m.

**Pull request merged**
